pub const SCRYPTO_TYPE_U256: u8 = 0x80;
pub const SCRYPTO_TYPE_ADDRESS: u8 = 0x81;
pub const SCRYPTO_TYPE_H256: u8 = 0x82;
pub const SCRYPTO_TYPE_BID: u8 = 0x83;
pub const SCRYPTO_TYPE_RID: u8 = 0x84;
pub const SCRYPTO_TYPE_TOKENS: u8 = 0x90;
pub const SCRYPTO_TYPE_TOKENS_REF: u8 = 0x91;
pub const SCRYPTO_TYPE_BADGES: u8 = 0x92;
pub const SCRYPTO_TYPE_BADGES_REF: u8 = 0x93;

pub const SCRYPTO_NAME_U256: &'static str = "U256";
pub const SCRYPTO_NAME_ADDRESS: &'static str = "Address";
pub const SCRYPTO_NAME_H256: &'static str = "H256";
pub const SCRYPTO_NAME_BID: &'static str = "BID";
pub const SCRYPTO_NAME_RID: &'static str = "RID";
pub const SCRYPTO_NAME_TOKENS: &'static str = "Tokens";
pub const SCRYPTO_NAME_TOKENS_REF: &'static str = "TokensRef";
pub const SCRYPTO_NAME_BADGES: &'static str = "Badges";
pub const SCRYPTO_NAME_BADGES_REF: &'static str = "BadgesRef";
