use crate::model::*;
use crate::types::*;
use radix_engine_interface::api::types::{
    AuthZoneStackOffset, BucketOffset, ComponentOffset, EpochManagerOffset, GlobalOffset,
    KeyValueStoreOffset, NonFungibleStoreOffset, PackageOffset, ProofOffset, ResourceManagerOffset,
    SubstateOffset, VaultOffset, WorktopOffset,
};

#[derive(Debug)]
pub enum RENodeInit {
    Global(GlobalAddressSubstate),
    Bucket(BucketSubstate),
    Proof(ProofSubstate),
    AuthZoneStack(AuthZoneStackSubstate),
    FeeReserve(FeeReserveSubstate),
    Vault(VaultRuntimeSubstate),
    Worktop(WorktopSubstate),
    KeyValueStore(KeyValueStore),
    NonFungibleStore(NonFungibleStore),
    Identity(MetadataSubstate, AccessRulesChainSubstate),
    Component(
        ComponentInfoSubstate,
        ComponentStateSubstate,
        ComponentRoyaltyConfigSubstate,
        ComponentRoyaltyAccumulatorSubstate,
        MetadataSubstate,
        AccessRulesChainSubstate,
    ),
    Package(
        PackageInfoSubstate,
        PackageRoyaltyConfigSubstate,
        PackageRoyaltyAccumulatorSubstate,
        MetadataSubstate,
        AccessRulesChainSubstate,
    ),
    ResourceManager(
        ResourceManagerSubstate,
        MetadataSubstate,
        AccessRulesChainSubstate,
        AccessRulesChainSubstate,
    ),
    EpochManager(
        EpochManagerSubstate,
        ValidatorSetSubstate,
        ValidatorSetSubstate,
        AccessRulesChainSubstate,
    ),
    Validator(ValidatorSubstate, AccessRulesChainSubstate),
    Clock(
        CurrentTimeRoundedToMinutesSubstate,
        AccessRulesChainSubstate,
    ),
    TransactionRuntime(TransactionRuntimeSubstate),
    Logger(LoggerSubstate),
}

impl RENodeInit {
    pub fn to_substates(self) -> HashMap<(NodeModuleId, SubstateOffset), RuntimeSubstate> {
        let mut substates = HashMap::<(NodeModuleId, SubstateOffset), RuntimeSubstate>::new();
        match self {
            RENodeInit::Bucket(bucket) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Bucket(BucketOffset::Bucket),
                    ),
                    RuntimeSubstate::Bucket(bucket),
                );
            }
            RENodeInit::Proof(proof) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Proof(ProofOffset::Proof),
                    ),
                    RuntimeSubstate::Proof(proof),
                );
            }
            RENodeInit::AuthZoneStack(auth_zone) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::AuthZoneStack(AuthZoneStackOffset::AuthZoneStack),
                    ),
                    RuntimeSubstate::AuthZoneStack(auth_zone),
                );
            }
            RENodeInit::Global(global_node) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Global(GlobalOffset::Global),
                    ),
                    RuntimeSubstate::Global(global_node),
                );
            }
            RENodeInit::Vault(vault) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Vault(VaultOffset::Vault),
                    ),
                    vault.into(),
                );
            }
            RENodeInit::KeyValueStore(store) => {
                for (k, v) in store.loaded_entries {
                    substates.insert(
                        (
                            NodeModuleId::SELF,
                            SubstateOffset::KeyValueStore(KeyValueStoreOffset::Entry(k)),
                        ),
                        v.into(),
                    );
                }
            }
            RENodeInit::Identity(metadata, access_rules) => {
                substates.insert(
                    (
                        NodeModuleId::Metadata,
                        SubstateOffset::Metadata(MetadataOffset::Metadata),
                    ),
                    metadata.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
            }
            RENodeInit::Component(
                info,
                state,
                royalty_config,
                royalty_accumulator,
                metadata,
                access_rules,
            ) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Component(ComponentOffset::Info),
                    ),
                    info.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Component(ComponentOffset::State),
                    ),
                    state.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::ComponentRoyalty,
                        SubstateOffset::Royalty(RoyaltyOffset::RoyaltyConfig),
                    ),
                    royalty_config.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::ComponentRoyalty,
                        SubstateOffset::Royalty(RoyaltyOffset::RoyaltyAccumulator),
                    ),
                    royalty_accumulator.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::Metadata,
                        SubstateOffset::Metadata(MetadataOffset::Metadata),
                    ),
                    metadata.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
            }
            RENodeInit::Worktop(worktop) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Worktop(WorktopOffset::Worktop),
                    ),
                    RuntimeSubstate::Worktop(worktop),
                );
            }
            RENodeInit::Logger(logger) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Logger(LoggerOffset::Logger),
                    ),
                    RuntimeSubstate::Logger(logger),
                );
            }
            RENodeInit::Package(
                package_info,
                package_royalty_config,
                package_royalty_accumulator,
                metadata,
                access_rules,
            ) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Package(PackageOffset::Info),
                    ),
                    package_info.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::PackageRoyalty,
                        SubstateOffset::Royalty(RoyaltyOffset::RoyaltyConfig),
                    ),
                    package_royalty_config.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::PackageRoyalty,
                        SubstateOffset::Royalty(RoyaltyOffset::RoyaltyAccumulator),
                    ),
                    package_royalty_accumulator.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::Metadata,
                        SubstateOffset::Metadata(MetadataOffset::Metadata),
                    ),
                    metadata.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
            }
            RENodeInit::ResourceManager(
                resource_manager,
                metadata,
                access_rules,
                vault_access_rules,
            ) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::ResourceManager(ResourceManagerOffset::ResourceManager),
                    ),
                    resource_manager.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::Metadata,
                        SubstateOffset::Metadata(MetadataOffset::Metadata),
                    ),
                    metadata.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
                // TODO: Figure out what the right abstraction is for vault access rules
                substates.insert(
                    (
                        NodeModuleId::VaultAccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    vault_access_rules.into(),
                );
            }
            RENodeInit::Validator(validator, access_rules) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Validator(ValidatorOffset::Validator),
                    ),
                    validator.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
            }
            RENodeInit::NonFungibleStore(non_fungible_store) => {
                for (id, non_fungible) in non_fungible_store.loaded_non_fungibles {
                    substates.insert(
                        (
                            NodeModuleId::SELF,
                            SubstateOffset::NonFungibleStore(NonFungibleStoreOffset::Entry(id)),
                        ),
                        non_fungible.into(),
                    );
                }
            }
            RENodeInit::EpochManager(
                epoch_manager,
                current_validator_set_substate,
                preparing_validator_set_substate,
                access_rules,
            ) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::EpochManager(EpochManagerOffset::EpochManager),
                    ),
                    epoch_manager.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::EpochManager(EpochManagerOffset::CurrentValidatorSet),
                    ),
                    current_validator_set_substate.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::EpochManager(EpochManagerOffset::PreparingValidatorSet),
                    ),
                    preparing_validator_set_substate.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules.into(),
                );
            }
            RENodeInit::Clock(current_time_rounded_to_minutes_substate, access_rules_substate) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::Clock(ClockOffset::CurrentTimeRoundedToMinutes),
                    ),
                    current_time_rounded_to_minutes_substate.into(),
                );
                substates.insert(
                    (
                        NodeModuleId::AccessRules,
                        SubstateOffset::AccessRulesChain(AccessRulesChainOffset::AccessRulesChain),
                    ),
                    access_rules_substate.into(),
                );
            }
            RENodeInit::FeeReserve(fee_reserve) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::FeeReserve(FeeReserveOffset::FeeReserve),
                    ),
                    fee_reserve.into(),
                );
            }
            RENodeInit::TransactionRuntime(transaction_hash) => {
                substates.insert(
                    (
                        NodeModuleId::SELF,
                        SubstateOffset::TransactionRuntime(
                            TransactionRuntimeOffset::TransactionRuntime,
                        ),
                    ),
                    transaction_hash.into(),
                );
            }
        }

        substates
    }
}
