pub const TRANSACTION_VERSION_V1: u8 = 1;
pub const MAX_NUMBER_OF_INTENT_SIGNATURES: usize = 16;
pub const DEFAULT_MAX_EPOCH_RANGE: u64 = 100;
pub const DEFAULT_COST_UNIT_LIMIT: u32 = 100_000_000;
pub const DEFAULT_MIN_TIP_PERCENTAGE: u32 = 0;
