[package]
name = "radix-engine-stores"
version = "0.6.0"
edition = "2021"

[dependencies]
radix-engine = { path = "../radix-engine" }
scrypto = { path = "../scrypto" }
sbor = { path = "../sbor" }
rocksdb = { version = "0.19.0" }
