pub const METADATA_VALUE_STRING_DISCRIMINATOR: u8 = 0u8;
pub const METADATA_VALUE_BOOLEAN_DISCRIMINATOR: u8 = 1u8;
pub const METADATA_VALUE_U8_DISCRIMINATOR: u8 = 2u8;
pub const METADATA_VALUE_U32_DISCRIMINATOR: u8 = 3u8;
pub const METADATA_VALUE_U64_DISCRIMINATOR: u8 = 4u8;
pub const METADATA_VALUE_I32_DISCRIMINATOR: u8 = 5u8;
pub const METADATA_VALUE_I64_DISCRIMINATOR: u8 = 6u8;
pub const METADATA_VALUE_DECIMAL_DISCRIMINATOR: u8 = 7u8;
pub const METADATA_VALUE_GLOBAL_ADDRESS_DISCRIMINATOR: u8 = 8u8;
pub const METADATA_VALUE_PUBLIC_KEY_DISCRIMINATOR: u8 = 9u8;
pub const METADATA_VALUE_NON_FUNGIBLE_GLOBAL_ID_DISCRIMINATOR: u8 = 10u8;
pub const METADATA_VALUE_NON_FUNGIBLE_LOCAL_ID_DISCRIMINATOR: u8 = 11u8;
pub const METADATA_VALUE_INSTANT_DISCRIMINATOR: u8 = 12u8;
pub const METADATA_VALUE_URL_DISCRIMINATOR: u8 = 13u8;
pub const METADATA_VALUE_ORIGIN_DISCRIMINATOR: u8 = 14u8;
pub const METADATA_VALUE_PUBLIC_KEY_HASH_DISCRIMINATOR: u8 = 15u8;

pub const METADATA_DISCRIMINATOR_ARRAY_BASE: u8 = 0x80;

pub const METADATA_VALUE_STRING_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 0u8;
pub const METADATA_VALUE_BOOLEAN_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 1u8;
pub const METADATA_VALUE_U8_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 2u8;
pub const METADATA_VALUE_U32_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 3u8;
pub const METADATA_VALUE_U64_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 4u8;
pub const METADATA_VALUE_I32_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 5u8;
pub const METADATA_VALUE_I64_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 6u8;
pub const METADATA_VALUE_DECIMAL_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 7u8;
pub const METADATA_VALUE_GLOBAL_ADDRESS_ARRAY_DISCRIMINATOR: u8 =
    METADATA_DISCRIMINATOR_ARRAY_BASE + 8u8;
pub const METADATA_VALUE_PUBLIC_KEY_ARRAY_DISCRIMINATOR: u8 =
    METADATA_DISCRIMINATOR_ARRAY_BASE + 9u8;
pub const METADATA_VALUE_NON_FUNGIBLE_GLOBAL_ID_ARRAY_DISCRIMINATOR: u8 =
    METADATA_DISCRIMINATOR_ARRAY_BASE + 10u8;
pub const METADATA_VALUE_NON_FUNGIBLE_LOCAL_ID_ARRAY_DISCRIMINATOR: u8 =
    METADATA_DISCRIMINATOR_ARRAY_BASE + 11u8;
pub const METADATA_VALUE_INSTANT_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 12u8;
pub const METADATA_VALUE_URL_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 13u8;
pub const METADATA_VALUE_ORIGIN_ARRAY_DISCRIMINATOR: u8 = METADATA_DISCRIMINATOR_ARRAY_BASE + 14u8;
pub const METADATA_VALUE_PUBLIC_KEY_HASH_ARRAY_DISCRIMINATOR: u8 =
    METADATA_DISCRIMINATOR_ARRAY_BASE + 15u8;
